title: Blossom Lemon # your name (or website title) here
logo: "/images/IMG_0861.JPG?" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Keep calm and always be a learner. 
  <br><br>
  I believe that Natural is an arrow passing through a multitude of randoms. And so I'm learning Data.
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
