title: Blossom Lemon
logo: "/images/IMG_0861.JPG?" 
description: > 
  Keep calm and always be a learner. 
  <br><br>
  I believe that Natural is an arrow passing through a multitude of randoms. And so I'm learning Data.
  <br><br>
  
  
theme: jekyll-theme-minimal

